### ISSUE TITLE
CrewCompare Compare 'Person' ['names'] Issue

### ISSUE THREAD

**Issue by akiva17** [akiva17/Movie-Cast-Crew#4]
I need to compare the names of the objects in movie1 and movie2list to see if they're the same and just spit out whichever ones match. It is currently running into a TypeError where the 'Person' object isn't callable. And both of the lists are filled with 'Person' objects. SO I may have to edit the big ugly lines of if statements. Or find some other crafty way of extracting the strings of names from the person objects

**Comment by halkony** [comment]
Try opening these issues with code snippets, it makes discussion far easier.

Please stop writing 10+ if statements. You should adapt #1 to store the data for comparison instead of printing it. Anytime you duplicate code, consider if you need a function instead. Duplicate code is difficult for others to maintain.

Consider researching classes to group data and behaviors.
https://realpython.com/python3-object-oriented-programming/

**Comment by akiva17** [comment]
I'll figure out the best way to work with the improved loop, maybe I'll see if I can make it more flexible with RolesLists first before I start making lists with the names.

**Comment by akiva17** [comment]
I was able to manipulate the search function in a way that the code can now feed back the names of workers for each movie accurately without 60 if statements. Using the person.get functions earlier in the program was the best way to call the parts of the Person object we needed. As this fixes the original issue here, marking this as Closed.
